config/routes.rb
Rails.application.routes.draw do

  get '/urls', to: 'urls#index'
  get '/urls/new', to: 'urls#new'
  post '/urls/create', to: 'urls#create'
  # get '/urls/:id', to: 'urls#show'
  # get '/urls/:id/edit' to: 'urls#edit'
  # patch '/urls/:id' to: 'urls#update'
  # delete '/urls/:id' to: 'urls#destroy' 
  get 'urls/:id/:short_url' => "urls#short_url"

 
end

app/models/url.rb
class Url < ActiveRecord::Base

  def self.generate_url

    array = Array.new(7){[*"A".."Z", *"a".."z", *"0".."9"].sample}.join
    return array
   
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  
  def index
    @urls = Url.all
  end

  def new
    @url = Url.new
  end

  def create
    short_url = Url.generate_url
    p params
    long_url = params[:url][:long_url]
    new_url = Url.new(long_url: long_url, short_url: short_url)

    if new_url.save
      redirect_to :action => :index
    else
      redirect_to '/new'
    end  
  end

  def show
    @url = Url.find([:id])
  end 
  
  def short_url
    @url =  Url.find_by(short_url: params[:short_url])
    visitas = @url.click_count + 1
    @url.update(click_count: visitas)
    redirect_to(@url.long_url)
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bitly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/urls/index.html.erb
 <h1>Bienvenido a bitly pirata!</h1>
 <%= link_to "New", urls_new_path(@url) %>
<div class="urls">
  <table>
    <tr>
      <th>Long Url</th>
      <th>Short Url</th>
    </tr>
    <tr>
  <% @urls.each do |url| %>
      <td><%= url.long_url %></td>
      <td>
<%= link_to "#{url.short_url}", "/urls/#{url.id}/#{url.short_url}" %></td>
    </tr>
    <% end %>
  </table>
</div>

  

app/views/urls/new.html.erb
<div class="container">
  <h2>Introduce tu url</h2>
  
  <%= form_for :url, :url => { :action => :create } do |f| %>

  <div class="field">
    <%= f.label :long_url %>
    <%= f.text_field :long_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>

  </div>